services:
  frontend:
    build: ./frontend
    image: learningwithai_frontend:latest
    container_name: learningwithai-frontend
    environment:
      - BACKEND_URL=http://backend:8000
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - learningwithai-network
  backend:
    build: ./backend
    image: learningwithai_backend:latest
    container_name: learningwithai-backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ITEMAI_URL=http://host.docker.internal:1234
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    networks:
      - learningwithai-network
  mongodb:
    image: mongo:latest
    container_name: learningwithai-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - learningwithai-network

volumes:
  mongodb_data: 

networks:
  learningwithai-network:
    driver: bridge