import os
import subprocess
import tempfile
import shutil
import time
from pathlib import Path
from typing import Dict, Any, Optional
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
import git
from backend.env_config import EnvConfig

router = APIRouter(prefix="/cursor-agent", tags=["Cursor Agent"])

class CloneRepoRequest(BaseModel):
    repo_url: str
    branch: Optional[str] = "main"

class LaunchAnalysisRequest(BaseModel):
    repo_path: str
    repo_url: str

class GetReadmeRequest(BaseModel):
    repo_path: str

@router.post("/clone-repo")
async def clone_repository(request: CloneRepoRequest) -> Dict[str, Any]:
    """
    Clone a repository to a local temporary directory
    """
    try:
        # Create a temporary directory for the repository
        temp_dir = tempfile.mkdtemp(prefix="cursor_agent_")
        repo_name = request.repo_url.split('/')[-1].replace('.git', '')
        repo_path = os.path.join(temp_dir, repo_name)
        
        print(f"Cloning {request.repo_url} to {repo_path}")
        
        # Clone the repository
        if request.branch and request.branch != "main":
            # Clone specific branch
            repo = git.Repo.clone_from(
                request.repo_url, 
                repo_path, 
                branch=request.branch,
                depth=1  # Shallow clone for speed
            )
        else:
            # Clone main branch
            repo = git.Repo.clone_from(
                request.repo_url, 
                repo_path,
                depth=1  # Shallow clone for speed
            )
        
        print(f"Successfully cloned repository to {repo_path}")
        
        return {
            "status": "success",
            "repo_path": repo_path,
            "temp_dir": temp_dir,
            "message": f"Repository cloned successfully to {repo_path}"
        }
        
    except git.exc.GitCommandError as e:
        print(f"Git clone error: {e}")
        raise HTTPException(status_code=400, detail=f"Failed to clone repository: {str(e)}")
    except Exception as e:
        print(f"Unexpected error during cloning: {e}")
        raise HTTPException(status_code=500, detail=f"Unexpected error: {str(e)}")

@router.post("/launch-analysis")
async def launch_cursor_analysis(request: LaunchAnalysisRequest) -> Dict[str, Any]:
    """
    Launch Cursor AI to analyze the repository and generate documentation
    """
    try:
        repo_path = request.repo_path
        
        if not os.path.exists(repo_path):
            raise HTTPException(status_code=404, detail="Repository path not found")
        
        print(f"Launching Cursor AI analysis for {repo_path}")
        
        # Check if Cursor AI is installed
        cursor_installed = await check_cursor_installation()
        if not cursor_installed:
            raise HTTPException(
                status_code=400, 
                detail="Cursor AI is not installed or not accessible. Please install Cursor AI first."
            )
        
        # Launch Cursor AI with the repository
        success = await launch_cursor_with_repo(repo_path, request.repo_url)
        
        if success:
            return {
                "status": "success",
                "message": "Cursor AI analysis launched successfully",
                "repo_path": repo_path
            }
        else:
            raise HTTPException(status_code=500, detail="Failed to launch Cursor AI analysis")
            
    except HTTPException:
        raise
    except Exception as e:
        print(f"Error launching Cursor AI analysis: {e}")
        raise HTTPException(status_code=500, detail=f"Unexpected error: {str(e)}")

@router.get("/get-readme")
async def get_readme_content(repo_path: str) -> Dict[str, Any]:
    """
    Retrieve the README.md file generated by Cursor AI
    """
    try:
        if not repo_path:
            raise HTTPException(status_code=400, detail="Repository path is required")
        
        readme_path = os.path.join(repo_path, "README.md")
        
        if os.path.exists(readme_path):
            with open(readme_path, 'r', encoding='utf-8') as f:
                content = f.read()
            
            return {
                "status": "success",
                "content": content,
                "file_path": readme_path
            }
        else:
            # Check for alternative README files
            alternative_names = ["README.txt", "readme.md", "Readme.md", "README.MD"]
            for alt_name in alternative_names:
                alt_path = os.path.join(repo_path, alt_name)
                if os.path.exists(alt_path):
                    with open(alt_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                    return {
                        "status": "success",
                        "content": content,
                        "file_path": alt_path
                    }
            
            return {
                "status": "not_found",
                "content": None,
                "message": "No README file found in the repository"
            }
            
    except Exception as e:
        print(f"Error reading README file: {e}")
        raise HTTPException(status_code=500, detail=f"Error reading README: {str(e)}")

@router.post("/cleanup")
async def cleanup_temp_directory(temp_dir: str) -> Dict[str, Any]:
    """
    Clean up temporary directory after analysis
    """
    try:
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
            return {
                "status": "success",
                "message": f"Cleaned up temporary directory: {temp_dir}"
            }
        else:
            return {
                "status": "not_found",
                "message": f"Temporary directory not found: {temp_dir}"
            }
    except Exception as e:
        print(f"Error cleaning up temporary directory: {e}")
        raise HTTPException(status_code=500, detail=f"Error during cleanup: {str(e)}")

async def check_cursor_installation() -> bool:
    """
    Check if Cursor AI is installed and accessible
    """
    try:
        # Try to run cursor --version
        result = subprocess.run(
            ["cursor", "--version"], 
            capture_output=True, 
            text=True, 
            timeout=10
        )
        return result.returncode == 0
    except (subprocess.TimeoutExpired, FileNotFoundError, subprocess.SubprocessError):
        return False

async def launch_cursor_with_repo(repo_path: str, repo_url: str) -> bool:
    """
    Launch Cursor AI with the repository and trigger documentation generation
    """
    try:
        # Change to the repository directory
        original_cwd = os.getcwd()
        os.chdir(repo_path)
        
        print(f"Changed to directory: {repo_path}")
        
        # Launch Cursor AI with the repository
        # This will open Cursor AI with the repository loaded
        cursor_process = subprocess.Popen(
            ["cursor", "."],
            cwd=repo_path,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )
        
        print(f"Cursor AI launched with PID: {cursor_process.pid}")
        
        # Wait a bit for Cursor AI to load
        time.sleep(5)
        
        # Here you would typically:
        # 1. Send commands to Cursor AI to generate documentation
        # 2. Wait for the documentation to be generated
        # 3. Close Cursor AI
        
        # For now, we'll simulate the process
        # In a real implementation, you might use:
        # - Cursor AI's CLI commands
        # - Automation scripts
        # - API calls if available
        
        # Simulate documentation generation
        await simulate_documentation_generation(repo_path, repo_url)
        
        # Close Cursor AI
        cursor_process.terminate()
        cursor_process.wait(timeout=10)
        
        # Restore original directory
        os.chdir(original_cwd)
        
        return True
        
    except Exception as e:
        print(f"Error launching Cursor AI: {e}")
        return False

async def simulate_documentation_generation(repo_path: str, repo_url: str) -> None:
    """
    Simulate the documentation generation process
    In a real implementation, this would trigger Cursor AI to generate documentation
    """
    try:
        # Create a sample README.md file
        repo_name = repo_url.split('/')[-1].replace('.git', '')
        
        readme_content = f"""# {repo_name}

## Overview
This repository was analyzed using Cursor AI for comprehensive documentation generation.

## Repository Information
- **Source**: {repo_url}
- **Analysis Tool**: Cursor AI Local Agent
- **Analysis Date**: {time.strftime('%Y-%m-%d %H:%M:%S')}

## Project Structure
This project has been analyzed by Cursor AI to provide comprehensive documentation.

## Features
- Professional documentation generation
- Code analysis and insights
- Architecture pattern recognition
- Best practices recommendations

## Getting Started
1. Clone the repository
2. Follow the project-specific setup instructions
3. Refer to the generated documentation for detailed information

## Analysis Details
This documentation was automatically generated using Cursor AI's advanced analysis capabilities, providing:
- Code quality assessment
- Architecture pattern identification
- Security considerations
- Performance recommendations
- Best practices guidance

## Contributing
Please refer to the original repository for contribution guidelines.

---
*Documentation generated by Cursor AI Agent*
"""
        
        readme_path = os.path.join(repo_path, "README.md")
        with open(readme_path, 'w', encoding='utf-8') as f:
            f.write(readme_content)
        
        print(f"Generated README.md at {readme_path}")
        
    except Exception as e:
        print(f"Error generating documentation: {e}")
        raise 