"""
Council Agent Slack Integration
Publish Council Briefs to Slack channels
"""

import os
import httpx

SLACK_BOT_TOKEN = os.getenv("SLACK_BOT_TOKEN")
SLACK_CHANNEL_ID = os.getenv("SLACK_CHANNEL_ID", "#council-briefs")

async def publish(payload: dict) -> str:
    """Publish Council Brief to Slack"""
    if not SLACK_BOT_TOKEN:
        # Return a mock response when Slack is not configured
        return "slack:disabled"
    
    channel = payload.get("channel", SLACK_CHANNEL_ID)
    text = payload.get("text", "Council Brief")
    
    # Create Slack Block Kit message for Council Brief
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "🏛️ Council Brief"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Topic:* {payload.get('topic', 'Deliberation')}\n\n{text[:2000]}..."  # Truncate for Slack
            }
        },
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": "Generated by Council Agent | Multi-persona deliberation"
                }
            ]
        }
    ]
    
    message_payload = {
        "channel": channel,
        "blocks": blocks,
        "text": f"Council Brief: {payload.get('topic', 'Deliberation')}"  # Fallback text
    }
    
    async with httpx.AsyncClient() as client:
        response = await client.post(
            "https://slack.com/api/chat.postMessage",
            headers={
                "Authorization": f"Bearer {SLACK_BOT_TOKEN}",
                "Content-Type": "application/json"
            },
            json=message_payload
        )
        response.raise_for_status()
        data = response.json()
        
        if not data.get("ok"):
            raise RuntimeError(f"Slack API error: {data}")
        
        return data.get("ts", "slack:ok")
